apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: pg
data:
  DATABASE_HOST: pg
  DATABASE_PORT: 5432
  DATABASE_USER: root
  DATABASE_PASSWORD: password
  DATABASE_NAME: postgres